### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by lancent100** [gnuns/AllOrigins#23]
I get a strange error message when running this on a private host.

Config:
Node V6.9.0
Ubuntu server

Error message:
```
/workspaces/AllOrigins$ node server.js
/home/lancent/workspaces/AllOrigins/lib/index.js:7
async function processRequest (req, res) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lancent/workspaces/AllOrigins/server.js:8:21)
    at Module._compile (module.js:570:32)
```

**Comment by gnuns** [comment]
Hi, @lancent100! AllOrigins uses the async/await feature, so it requires Node.js v8.0.0+

**Comment by lancent100** [comment]
@gnuns : Thank you! It works like a charm! ;-)
