### ISSUE TITLE
Fresh Build/Install Failing

### ISSUE THREAD

**Issue by computeronix** [gnuns/allOrigins#76]
I am attempting a fresh install/build using npm install on my server and its failing.

Below is the log.  It looks like the repro has this tagged as failing to build after the latest commit too.

loadDep:iconv-lite → get  ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine got@11.8.2: wanted: {"node":">=10.19.0"} (current: {"node":"8.10.0",loadDep:responselike → re ▌ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine decompress-response@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine cacheable-lookup@5.0.4: wanted: {"node":">=10.6.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine http2-wrapper@1.0.3: wanted: {"node":">=10.19.0"} (current: {"node":loadDep:responselike → ad ▀ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @szmarczak/http-timer@4.0.5: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @sindresorhus/is@4.0.1: wanted: {"node":">=10"} (current: {"node":"8loadDep:defer-to-connect  ▐ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine defer-to-connect@2.0.1: wanted: {"node":">=10"} (current: {"node":"8loadDep:json-buffer → res ▀ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine mimic-response@3.1.0: wanted: {"node":">=10"} (current: {"node":"8.1loadDep:resolve-alpn → 30 ▌ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine quick-lru@5.1.1: wanted: {"node":">=10"} (current: {"node":"8.10.0",loadDevDep:vpdate → 304   ▀ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine nock@13.0.11: wanted: {"node":">= 10.13"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest@26.6.3: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine prettier@2.3.0: wanted: {"node":">=10.13.0"} (current: {"node":"8.10loadDep:jest-cli → addNam ▐ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine jest-cli@26.6.3: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jest/core@26.6.3: wanted: {"node":">= 10.14.2"} (current: {"node":"loadDep:strip-ansi → 304  ▌ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine chalk@4.1.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-runner@26.6.3: wanted: {"node":">= 10.14.2"} (current: {"node":loadDep:strip-ansi → cach ▌ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine jest-resolve-dependencies@26.6.3: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-haste-map@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-changed-files@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-watcher@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-snapshot@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-runtime@26.6.3: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-regex-util@26.0.0: wanted: {"node":">= 10.14.2"} (current: {"noloadDep:strip-ansi → reso ▄ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine jest-config@26.6.3: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-util@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-message-util@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine jest-validate@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jest/console@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jest/types@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":loadDep:strip-ansi → cach ▀ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @jest/reporters@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jest/test-result@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @jest/transform@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"noloadDep:strip-ansi → cach ▀ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine jest-resolve@26.6.2: wanted: {"node":">= 10.14.2"} (current: {"node"loadDep:stack-utils → req ▄ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine stack-utils@2.0.3: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine pretty-format@26.6.2: wanted: {"node":">= 10"} (current: {"node":"8.loadDep:node-notifier → 3 ▐ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine string-length@4.0.2: wanted: {"node":">=10"} (current: {"node":"8.10loadDep:node-notifier → 3 ▄ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine jest-worker@26.6.2: wanted: {"node":">= 10.13.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine v8-to-istanbul@7.1.2: wanted: {"node":">=10.10.0"} (current: {"node"npm ERR! Linux 5.4.0-1047
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/AllOrigins/npm-debug.log

**Comment by computeronix** [comment]
Moved to latest ubuntu version 20 and resolved this
