### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by ali-apadana** [gnuns/allOrigins#84]
Hi
I have this error : 

> allorigins@2.5.1 start /home/mazeroon/public_html/AllOrigins
> node server.js

/home/mazeroon/public_html/AllOrigins/app/logger.js:16
          to: to?.hostname,
                 ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mazeroon/public_html/AllOrigins/app/process-request.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! allorigins@2.5.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the allorigins@2.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-06T07_47_25_899Z-debug.log

**Comment by gnuns** [comment]
Hi, @ali-apadana!
Which Node.js version are you using? AllOrigins requires Node.js 14.5+.
You can check the installed version with `node -v`.
